# Generated by Django 4.1.5 on 2023-01-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_nftcard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftcard',
            name='tag',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
